version: '3.5'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb-taskforce-users
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_ROOT_DATABASE: taskforce-users
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db

  mongdb-express:
    image: mongo-express
    restart: always
    container_name: mongo-express-taskforce-users
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://admin:123456@mongodb:27017/
